language: php

php:
  - 5.6
  - 7
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

sudo: false

install:
  - composer selfupdate
  - composer install

script:
  - composer test

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
