#!/usr/bin/env php
<?php
error_reporting(E_ALL);
ini_set('display_errors', true);

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

/*
 * For PHPUNIT_COMPOSER_INSTALL:
 *   + see phpunit executable and
 *   + see PHPUnit_Framework_TestCase::run
 */
foreach ([
    __DIR__.'/../../autoload.php',
    __DIR__.'/../vendor/autoload.php',
    __DIR__.'/vendor/autoload.php'
    ] as $file) {

    if (file_exists($file)) {
        define('PHPUNIT_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

require PHPUNIT_COMPOSER_INSTALL;

$bootstrap = '';
foreach ([
    getcwd().'/tests/bootstrap.php',
    getcwd().'/vendor/autoload.php',
    ] as $file) {

    if (file_exists($file)) {
        $bootstrap = '--bootstrap='.$file;

        break;
    }
}

$_SERVER['argv'] = [
    $_SERVER['argv'][0],
    '--configuration='.__DIR__.'/phpunit.xml.dist',
    $bootstrap,
    '--coverage-html='.getcwd().'/build/coverage',
    '--coverage-clover='.getcwd().'/build/logs/clover.xml',
    '--whitelist='.getcwd().'/src',
    getcwd().'/tests',
];

if (class_exists(PHPUnit_TextUI_Command::class)) {
    PHPUnit_TextUI_Command::main();
} else {
    PHPUnit\TextUI\Command::main();
}
